// Lista de preguntas para el Drill de la Lección 3
// Incluye cantidades y precios objetivo entre paréntesis para referencia.

export const LESSON_3_QUESTIONS: string[] = [
  "Hey! What's up?",
  "How do you say \"No entendí\"?",
  "How do you say \"Repite, por favor\"?",
  "How do you say \"Más despacio por favor\"?",
  "What is your favorite music?",
  "Do you like Ray Charles' music?",
  "How many couches are there? (3)",
  "How many coffee tables are there? (1)",
  "How many pillows are there? (5)",
  "How many plants are there? (6)",
  "How many plates are there? (6)",
  "How much do the plates cost? ($21)",
  "How many forks are there? (12)",
  "How much do the forks cost? ($25)",
  "How many spoons are there? (24)",
  "How much do the spoons cost? ($31)",
  "How many knives are there? (6)",
  "How much do the knives cost? ($28)",
  "How do you say \"Paquete de chicles\"?",
  "How do you say \"Botella de agua\"?",
  "How do you say \"Botella de refresco\"?",
  "How do you say \"Lata de cerveza\"?",
  "How do you say \"Bolsa de papitas\"?",
  "How do you say \"Bolsa de caramelos\"?",
  "Do you like motorcycles?",
  "Do you prefer a car or a motorcycle?",
  "Do you like summer?",
  "What season do you prefer?",
  "Do you like Rock music?",
  "What kind of music do you prefer?",
  "Do you like to read?",
  "What type of book do you like to read?",
  "Do you like hot weather?",
  "Do you like cold weather?",
  "Do you like rainy weather?",
  "Do you like snowy weather?",
  "Do you like animals?",
  "Do you like funny movies?",
  "Do you like Ray Charles' music?",
  "What is your favorite activity?",
  "What is your favorite animal?",
  "What is your favorite country?",
  "What is your favorite music?",
  "How do you say \"un perro grande\"?",
  "How do you say \"manzanas pequeñas\"?",
  "How do you say \"un gato feo\"?",
  "How do you say \"gatos hermosos\"?",
  "How do you say \"un auto viejo\"?",
  "How do you say \"autos nuevos\"?",
  "How do you say \"un reloj caro\"?",
  "How do you say \"relojes baratos\"?",
  "How do you say \"un hombre rico\"?",
  "How do you say \"hombres pobres\"?",
  "How do you say \"un buen estudiante\"?",
  "How do you say \"malos estudiantes\"?",
  "Is the beach beautiful?",
  "Do you prefer the beach or the mountains?",
  "Is social media fun?",
  "What is your favorite app?",
  "Is beer good?",
  "Do you like beer or wine more?",
  "Is fast food bad?",
  "What kind of fast food do you dislike?",
  "Is the city of Denver old?",
  "What is your favorite city?",
  "Is Scarlett Johansson ugly?",
  "Who is your favorite actor or actress?",
  "Are cartoons popular?",
  "Do you like cartoons?",
  "Is wine delicious?",
  "Do you like white wine or red wine?"
];